In [ ]:
import kagglehub


path = kagglehub.dataset_download("datascikhan/diabetes")

print("Path to dataset files:", path)

:

In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv("/root/.cache/kagglehub/datasets/datascikhan/diabetes/versions/1/diabetes_large_dataset.csv")
df.head()

,patient_id,record_id,age,age_group,sex,gender,ethnicity,race_group,marital_status,education_level,...,diabetes_risk_score,overall_health_score,physical_health_score,mental_wellbeing_score,quality_of_life_score,chronic_condition_count,hospitalization_history,emergency_visit_history,diabetes_status,diabetes_type
0,P000001,R00000001,57.0,51-60,Male,Male,Black,Black,Married,Some College,...,2.4,86.8,86.0,64.7,89.4,1,2,0,NaN,No Diabetes
1,P000002,R00000002,47.0,41-50,Female,Female,White,White,Married,High School,...,2.7,85.5,86.2,78.4,80.0,3,0,0,NaN,No Diabetes
2,P000003,R00000003,59.0,51-60,Male,Male,Black,Black,Married,Some College,...,19.3,66.0,66.1,56.7,64.7,2,0,1,1.0,Type 2
3,P000004,R00000004,72.0,71-90,Female,Female,Black,Black,Single,Master,...,0.9,61.8,64.4,68.6,59.6,3,0,0,0.0,No Diabetes
4,P000005,R00000005,46.0,41-50,Male,Male,Hispanic,Hispanic,Married,Bachelor,...,6.3,80.4,81.8,73.0,76.7,1,0,2,0.0,No Diabetes

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Columns: 209 entries, patient_id to diabetes_type
dtypes: float64(102), int64(15), object(92)
memory usage: 159.5+ MB

In [ ]:
df.isnull().sum()

patient_id                    0
record_id                     0
age                        1993
age_group                     0
sex                        2005
                           ...
chronic_condition_count       0
hospitalization_history       0
emergency_visit_history       0
diabetes_status            2020
diabetes_type               547
Length: 209, dtype: int64

In [ ]:
df = df[[
    "age",
    "sex",
    "family_history_diabetes",
    "exercise_days_per_week",
    "bmi",
    "heart_rate",
    "diabetes_status"
]]

In [ ]:
df = df.dropna(subset=["diabetes_status"])
df["age"] = df["age"].fillna(df["age"].mean())

df["bmi"] = df["bmi"].fillna(df["bmi"].mean())

df["exercise_days_per_week"] = df["exercise_days_per_week"].fillna(
    df["exercise_days_per_week"].mean()
)

df["heart_rate"] = df["heart_rate"].fillna(df["heart_rate"].mean())

In [ ]:
print(df.columns.tolist())

['age', 'exercise_days_per_week', 'bmi', 'heart_rate', 'diabetes_status', 'sex_Female', 'sex_Male', 'family_history_diabetes_No', 'family_history_diabetes_Yes']

In [ ]:
X = df.drop("diabetes_status", axis=1)

y = df["diabetes_status"]
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)
y_pred = model.predict(X_test)
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy using logistic regression:", accuracy * 100, "%")

Accuracy using logistic regression: 79.76117575015309 %

In [ ]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier(random_state=42)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy using Decision Tree:", accuracy * 100, "%")

Accuracy using Decision Tree: 68.80485813431314 %

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

model = KNeighborsClassifier(n_neighbors=5)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy using KNN:", accuracy * 100, "%")

Accuracy using KNN: 76.17370892018779 %

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

model = RandomForestClassifier(n_estimators=100, random_state=42)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy using Random Forest:", accuracy * 100, "%")

Accuracy using Random Forest: 77.93937538273117 %

In [ ]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

model = SVC(kernel="linear")

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy using SVM:", accuracy * 100, "%")